import { searchState } from "@/atoms/SearchAtom";
import Hero from "@/components/Hero";
import PopularSection from "@/components/PopularSection";
import Search from "@/components/Search";
import Head from "next/head";
import { useRecoilState } from "recoil";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <PopularSection />
      </main>
    </>
  );
}
